[package]
name = "benday"
version = "0.1.0"
edition = "2021"

[dependencies]
pg_sdl = { workspace = true }
sdl2 = { workspace = true }
nalgebra = { workspace = true }
as-any = { workspace = true }
models = { workspace = true }
